/** Category tree. Sub-categories carry a parentSlug and simulations may sit on either level. */
export const categories = [
  { slug: 'mechanics', name: '力学', description: '運動・力・エネルギー・振動・剛体', sortOrder: 10 },
  { slug: 'gravitation', name: '万有引力と天体力学', description: '重力・軌道・多体問題', sortOrder: 20 },
  { slug: 'electromagnetism', name: '電磁気学', description: '電場・磁場・回路・電磁誘導', sortOrder: 30 },
  { slug: 'electric-field', name: '電場', parentSlug: 'electromagnetism', description: '点電荷・電位・導体・誘電体', sortOrder: 31 },
  { slug: 'magnetic-field', name: '磁場', parentSlug: 'electromagnetism', description: '電流・ローレンツ力・荷電粒子', sortOrder: 32 },
  { slug: 'circuits', name: '回路', parentSlug: 'electromagnetism', description: 'オームの法則・過渡現象・共振', sortOrder: 33 },
  { slug: 'induction', name: '電磁誘導', parentSlug: 'electromagnetism', description: 'ファラデー・レンツ・発電機', sortOrder: 34 },
  { slug: 'waves-optics', name: '波動と光', description: '波・干渉・回折・レンズ・偏光', sortOrder: 40 },
  { slug: 'thermodynamics', name: '熱力学', description: '気体・熱機関・エントロピー', sortOrder: 50 },
  { slug: 'statistical-physics', name: '統計物理', description: 'ランダムウォーク・分布・相転移', sortOrder: 60 },
  { slug: 'fluids', name: '流体', description: '流れ・浮力・粘性・渦', sortOrder: 70 },
  { slug: 'chaos', name: 'カオスと非線形', description: '分岐・アトラクタ・フラクタル', sortOrder: 80 },
  { slug: 'relativity', name: '相対論', description: '特殊相対論・一般相対論', sortOrder: 90 },
  { slug: 'quantum', name: '量子力学', description: '波動関数・トンネル効果・原子', sortOrder: 100 },
  { slug: 'nuclear-particle', name: '原子核と素粒子', description: '崩壊・核反応・散乱', sortOrder: 110 },
  { slug: 'astrophysics', name: '天体物理', description: '恒星・惑星・銀河・宇宙論', sortOrder: 120 },
  { slug: 'stars', name: '恒星', parentSlug: 'astrophysics', description: '星形成・進化・終末', sortOrder: 121 },
  { slug: 'planets', name: '惑星', parentSlug: 'astrophysics', description: '惑星形成・大気・ハビタブルゾーン', sortOrder: 122 },
  { slug: 'galaxies', name: '銀河', parentSlug: 'astrophysics', description: '回転曲線・衝突・暗黒物質', sortOrder: 123 },
  { slug: 'cosmology', name: '宇宙論', parentSlug: 'astrophysics', description: '膨張・背景放射・構造形成', sortOrder: 124 },
  { slug: 'space-physics', name: '太陽・宇宙プラズマ', description: '太陽風・磁気圏・オーロラ', sortOrder: 130 },
];

/**
 * Tags are deliberately independent of the category tree: a simulation can be
 * tagged "chaos" while living under Mechanics. Admins can add, rename and
 * delete these freely.
 */
export const tags = [
  ['mechanics', '力学', '力と運動に関するもの'],
  ['kinematics', '運動学', '位置・速度・加速度の記述'],
  ['energy', 'エネルギー', 'エネルギーの変換と保存'],
  ['momentum', '運動量', '運動量と力積'],
  ['collision', '衝突', '弾性・非弾性衝突'],
  ['oscillation', '振動', '単振動・減衰・強制振動'],
  ['resonance', '共振', '共振とQ値'],
  ['normal-modes', '基準振動', '連成系のモード'],
  ['air-resistance', '空気抵抗', '速度に依存する抵抗力'],
  ['gravitation', '万有引力', '重力相互作用'],
  ['orbit', '軌道', '軌道運動と軌道要素'],
  ['celestial-mechanics', '天体力学', '天体の運動'],
  ['n-body', '多体問題', '3体以上の重力系'],
  ['satellite', '人工衛星', '衛星軌道と打ち上げ'],
  ['electromagnetism', '電磁気学', '電気と磁気'],
  ['electric-field', '電場', '電場と電位'],
  ['magnetic-field', '磁場', '磁場と磁力'],
  ['lorentz-force', 'ローレンツ力', '荷電粒子に働く力'],
  ['circuits', '回路', '電気回路'],
  ['capacitor', 'コンデンサー', '静電容量と充放電'],
  ['transient', '過渡現象', '定常状態に至る前の振る舞い'],
  ['induction', '電磁誘導', '磁束変化による起電力'],
  ['lenz-law', 'レンツの法則', '誘導の向き'],
  ['waves', '波動', '波の性質'],
  ['sound', '音波', '音の伝わり方'],
  ['optics', '光学', '光の伝播と結像'],
  ['interference', '干渉', '重ね合わせによる強弱'],
  ['doppler', 'ドップラー効果', '運動による振動数の変化'],
  ['thermodynamics', '熱力学', '熱と仕事'],
  ['kinetic-theory', '気体分子運動論', '分子運動から巨視量へ'],
  ['statistical-physics', '統計物理', '多数の粒子の統計的性質'],
  ['random-walk', 'ランダムウォーク', '確率的な移動'],
  ['diffusion', '拡散', '濃度勾配による広がり'],
  ['monte-carlo', 'モンテカルロ法', '乱数を使った数値計算'],
  ['chaos', 'カオス', '決定論的だが予測困難な系'],
  ['nonlinear', '非線形', '非線形方程式に従う系'],
  ['bifurcation', '分岐', 'パラメータによる質的変化'],
  ['relativity', '相対論', '相対性理論'],
  ['special-relativity', '特殊相対論', '慣性系と光速不変'],
  ['time-dilation', '時間の遅れ', '運動する時計の遅れ'],
  ['quantum', '量子力学', 'ミクロな世界の物理'],
  ['tunnelling', 'トンネル効果', '古典的に禁止された領域の透過'],
  ['wave-function', '波動関数', '量子状態の記述'],
  ['nuclear', '原子核', '原子核物理'],
  ['astrophysics', '天体物理', '天体と宇宙の物理'],
  ['galaxies', '銀河', '銀河の構造と力学'],
  ['dark-matter', '暗黒物質', '見えない質量'],
  ['dark-energy', 'ダークエネルギー', '宇宙の加速膨張'],
  ['cosmology', '宇宙論', '宇宙全体の進化'],
  ['plasma', 'プラズマ', '電離気体'],
  ['space', '宇宙', '宇宙空間に関するもの'],
  ['1d', '1次元', '1次元のシミュレーション'],
  ['2d', '2次元', '2次元のシミュレーション'],
  ['3d', '3次元', '3次元表示を含む'],
  ['numerical-simulation', '数値シミュレーション', '微分方程式の数値解法を使う'],
  ['visualization', '可視化', '場や分布の可視化'],
  ['model', 'モデル', '現象を単純化したモデル'],
  ['calculator', '計算機', '数値を入れて計算する道具'],
  ['experiment', '実験', '測定と解析を伴う実験'],
  ['measurement', '測定', 'データ取得と誤差評価'],
  ['high-school', '高校物理', '高校の範囲で理解できる'],
  ['university-physics', '大学物理', '大学以上の内容'],
].map(([slug, name, description]) => ({ slug, name, description }));
